version: "3.1"
services: 
    www:
        build: .
        ports:
            - "80:80"
        volumes: 
            - ./:/var/www/html
        links: 
            - db
        networks: 
            - default
    db:
        image: mysql:8.0
        ports: 
            - "3306:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_DATABASE: mydb
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
        volumes: 
            - ./mysql:/docker-entrypoint-initdb.db
            - ./mysql/conf:/etc/mysql/conf.db
            - persistent:/var/lib/mysql
        networks: 
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports: 
            - 8000:80
        environment: 
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
            MYSQL_ROOT_PASSWORD: root
volumes: 
    persistent: